### ISSUE TITLE
文章列表点击Continue reading，跳转到文章详情后是登录状态

### ISSUE THREAD

**Issue by sansx** [zzy/surfer#1]
看了一下代码，可能是因为Continue reading的链接是
`https://blog.budshome.com/budshome/rust-1.52.0-yi-zheng-shi-fa-bu-,ji-qi-xin-te-xing-xiang-shu`。
导致路由匹配到了
`let mut user = app.at("/:username");
user.at("/:slug").get(article_index);`
这段代码，然后点进文章详情就渲染成了`budshome`这个用户的登录状态的详情页。

**Comment by zzy** [comment]
@sansx 嗨，朋友。您好！首先感谢您的帮助哈。

你是否是说右上角显示的是登录状态？但是文章可以正常查阅吧？如果是这个问题，我是正打算这几天重拾这个开发的。
最近忙其它事情，这个仓库一直没顾得上 ;-) 🤝 

谢谢！

**Comment by sansx** [comment]
hh，客气了。
看了你的好多文章，帮个忙是应该的。
发现这个问题是因为看文章的时候，header那里有个图老是显示裂开，给我看的难受的不行。😂
clone下来之后看代码发现那里的图片应该显示的是用户头像，顺藤摸瓜找过去了，本来想自己改改提个pr的，然后因为我数据库没数据，所以跑不起来，一直panic，就只好先提个issue。

另外，问一下标题也改成链接体验是否会好一些，还有Topics里面的只有一篇的话，统计数字不显示不知道会不会好一些。

最后感谢一下老哥辛苦翻译和写的文章。🤝

**Comment by zzy** [comment]
@sansx 用 tide 的朋友太少了，tide 自己也还不成熟。主要是开发者都太忙，提交的 pr 也没人理。😂

如果您有时间帮忙，我可以给你开一个数据库哈。云上 mongodb 数据库之间数据复制很方便，可以同步我目前用的数据库。您如果也用，后面我可以再同步您的数据库。

我的微信是 yupen-com，如果需要数据加我哈，我传给你，或者直接开一个云数据库。

目前代码需要重构的太多了，特别是孙老师的 async-graphql 改进较多，我是从 async-graphql 1.x 开始用的。目前的很多普通对象，都可以精简代码为简单对象+复杂对象。

就打算后续认真重构下。

再次感谢！
